package com.quetzalcoatl.telebot.service;


import com.quetzalcoatl.telebot.response.Response;
import com.quetzalcoatl.telebot.util.MainUtil;
import org.slf4j.Logger;
import org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageText;
import org.telegram.telegrambots.meta.api.objects.Message;
import org.telegram.telegrambots.meta.api.objects.Update;
import java.util.List;
import static org.slf4j.LoggerFactory.getLogger;

public class ServiceImpl implements Service{
    private List<Response> responseList = MainUtil.getResponseList();
    private static final Logger log = getLogger(ServiceImpl.class);

    /**
     * Опрашивает все Response на возможность обработки входящего сообщения пользователя.
     * Запрашивает ответ для пользователя у первого подходящего Response.
     * Если подходящего ответа нет, возвращает null.
     */
    @Override
    public String getTextResponse(Update update) {
        String textResponse = null;
        String userRequest = update.getMessage().getText();
        //если не будет подходящего обработчика - response будет равен null
        Response response = responseList.stream()
                .filter(r -> r.isSuitable(userRequest))
                .findFirst()
                .orElse(null);
        if(response != null)
            textResponse = response.getText(update);//TODO: а если тут вернется null??? - при некорректной работе парсера, например
        //TODO: содержит текст? картинку? стикер? дефолт?

        log.debug("getTextResponse, returned null={}, response generated by {}", textResponse == null, response != null ? response.getClass().getSimpleName() : "null");
        return textResponse;
    }

    @Override
    public EditMessageText handleCallbackQuery(Update update) {
        return null;
    }

    @Override
    public Message sendInlineKeyboard(long chatID) {
        return null;
    }


}
